name: "Init Flutter"
description: "Initializes Flutter repo"
runs:
  using: "composite"
  steps:
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        architecture: x64
    - name: Generate code
      shell: bash
      run: dart run build_runner build