# The name of the workflow
name: Flutter

# The event that triggers the workflow
on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]
jobs:
  analysis:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Flutter
      - uses: ./.github/workflows/actions/initialize-flutter
      - name: Check Code Format
        run: dart format . --set-exit-if-changed
      - name: Analyze code
        run: dart analyze .
  widget-tests:
    name: widget-tests
    runs-on: ubuntu-latest
    needs: analysis
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Flutter
      - uses: ./.github/workflows/actions/initialize-flutter
      - name: Run tests
        run: flutter test
  build:
    name: build flutter app
    runs-on: ubuntu-latest
    needs: [analysis,widget-tests]
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Flutter
      - uses: ./.github/workflows/actions/initialize-flutter
      - name: Install dependencies
        run: flutter pub get
      - name: Build android apk and app bundle
        run: flutter build apk