# The name of the workflow
name: Flutter

# The event that triggers the workflow
on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]
jobs:

  build:
    name: analysis test bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Flutter
        uses: ./.github/workflows/actions/initialize-flutter
      - name: Check Code Format
        run: dart format . --set-exit-if-changed
      - name: Analyze code
        run: dart analyze .
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Build android apk and app bundle
        run: flutter build apk --debug
      - run: ls build/app/outputs/flutter-apk
      - name: Distribution app artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: share_trips_team
          file: build/app/output/flutter-apk/app-debug.apk