# The name of the workflow
name: Flutter

# The event that triggers the workflow
on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]
jobs:

  build:
    name: analysis test bundle
    runs-on: self-hosted
    steps:
#      - uses: actions/checkout@v3
#      - name: Initialize Flutter
#        uses: ./.github/workflows/actions/initialize-flutter
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.0.2
      - name: Install dependencies
        run: flutter pub get
      - name: Check Code Format
        run: dart format . --set-exit-if-changed
      - name: Analyze code
        run: dart analyze .
      - name: Run tests
        run: flutter test
      - name: Build android apk and app bundle
        run: flutter build apk --debug
      - run: ls build/app/outputs/flutter-apk
      - name: Distribution app artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: git_action_tester
          file: build/app/outputs/flutter-apk/app-debug.apk
